[package]
name = "atlaspack_plugin_namer_default"
version = "0.1.0"
edition = "2021"

[dependencies]
atlaspack_core = { path = "../atlaspack_core" }
anyhow = "1.0"
async-trait = "0.1"
pathdiff = "0.2"
serde = { version = "1.0", features = ["derive"] }

[dev-dependencies]
tokio = { version = "1.28.2", features = ["macros"] }
